http.listener.host=0.0.0.0
http.listener.port=8081

soap.protocol=https
soap.host=example.org
soap.port=443

soap.orders.path=/services/orders
soap.orders.update.path=/services/orders/update
soap.orderItems.path=/services/orderItems
soap.productLines.path=/services/productLines
soap.customers.path=/services/customers

soap.username=apiuser
soap.password=changeme
